---
pipeline:
  build:
    when:
      event:
      - push
      - pull_request
    image: maven:3-jdk-8
    commands:
    - mvn -B clean package
  publish_jar:
      image: jmccann/drone-artifactory
      repo_key: trepo-maven
      files:
        - target/*.jar
        
