---
pipeline:
  build:
    when:
      event:
      - push
      - pull_request
    image: maven:3-jdk-8
    commands:
    - mvn -B clean package
  publish_jar:
      image: athieriot/drone-artifactory
      environment:
        - DRONE_VERSION=0.8
        
