---
pipeline:
  build:
    when:
      event:
      - push
      - pull_request
    image: maven:3-jdk-8
    commands:
    - mvn -B clean package
  publish_jar:
      image: athieriot/drone-artifactory:latest
      url: http://35.200.216.88:8081/artifactory/webapp/#/artifacts/browse/tree/General/trepo-maven
      repo_key: trepo-maven
      files:
        - target/*.jar
      when:
        branch: master
