---
pipeline:
  check-build:
    image: ubuntu
    commands:
    - echo "Welcome To Drone World"
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: automation
    username: drone
    template: >
      {{#success build.status}}
      Hey Amar, build {{build.number}} succeed...
      {{else}}
      Hey Amar, build {{build.number}} Failed, fix me...
      {{/success}}
