---
pipeline:
  build:
    when:
      event:
      - push
      - pull_request
    image: maven:3-jdk-8
    commands:
    - mvn -B clean package
plugin:
    artifactory:
      image: athieriot/drone-artifactory
      url: http://35.200.216.88:8081
      username: admin
      password: admin 
      repo_key: trepo-maven
      files: 
        - target/*.jar
