---
pipeline:
  build:
    when:
      event:
      - push
      - pull_request
    image: maven:3-jdk-8
    commands:
    - mvn -B clean package
  publish_jar:
      image: athieriot/drone-artifactory
      environment:
        - DRONE_VERSION=0.8
      url: http://35.200.145.139:8081
      username: admin
      password: admin
      pom: pom.xml
      repo_key: trepo-maven
      force_upload: true
      files: 
      - target/*.jar
  publish-image:
    image: plugins/docker:17.05
    username: admin
    password: admin
    repo: amarbright/trepo
    tag: latest
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: automation
    username: drone
    template: >
      {{#success build.status}}
      Hey Amar, build {{build.number}} succeed & moved to Repo...
      {{else}}
      Hey Amar, build {{build.number}} Failed, fix me....!!!!!!!!.....
      {{/success}}
