---
pipeline:
  check-build:
    image: ubuntu
    commands:
    - echo "Welcome"
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: automation
    username: drone
    template: >
      {{#success build.status}}
      Hey Amar, build {{build.number}} succeed...
      {{else}}
      Hey Amar, build {{build.number}} Failed, fix me...
      {{/success}}
