---
pipeline:
  build:
    when:
      event:
      - push
      - pull_request
    image: maven:3-jdk-8
    commands:
    - mvn -B clean package
  publish_jar:
      image: athieriot/drone-artifactory
      environment:
        - DRONE_VERSION=0.8
      url: http://35.200.145.139:8081
      username: admin
      password: admin
      pom: pom.xml
      repo_key: trepo-maven
      force_upload: true
      files: 
      - target/*.jar
      - target/*.war
  publish-image:
    image: plugins/docker:17.05
    registry: http://35.200.145.139:8081
    repo: trepo
    tag: latest
