---
pipeline:
  build:
    when:
      event:
      - push
      - pull_request
    image: maven:3-jdk-8
    commands:
    - mvn -B clean package
  publish:
    image: plugins/docker
    repo: trepo-maven
    tags: latest
    files: 
      - target/*.jar
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: automation
    username: drone
    template: >
      {{#success build.status}}
      Hey Amar, build {{build.number}} succeed & moved to Repo...
      {{else}}
      Hey Amar, build {{build.number}} Failed, fix me....!!!!!!!!.....
      {{/success}}
