---
pipeline:
  build:
    when:
      event:
      - push
      - pull_request
    image: maven:3-jdk-8
    commands:
    - mvn -B clean package
  publish-image:
    image: plugins/docker:17.05
    environment:
        - DRONE_VERSION=0.8
    registry: http://35.200.145.139:8081
    repo: http://35.200.145.139:8081/artifactory/trepo
    tags: latest
    username: admin
    password: admin
    insecure: true
